// <auto-generated />
using System;
using LocalMarketplace.Models.DatabaseModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalMarketplace.Migrations.Product
{
    [DbContext(typeof(ProductContext))]
    [Migration("20190527150158_DataSchemaDatabase")]
    partial class DataSchemaDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LocalMarketplace.Models.DatabaseModels.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ProductId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("LocalMarketplace.Models.DatabaseModels.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category");

                    b.Property<string>("Contact");

                    b.Property<string>("Description");

                    b.Property<string>("Payment");

                    b.Property<string>("Title");

                    b.Property<string>("UserId");

                    b.Property<string>("WorkLength");

                    b.Property<string>("WorkType");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("LocalMarketplace.Models.DatabaseModels.Picture", b =>
                {
                    b.HasOne("LocalMarketplace.Models.DatabaseModels.Product", "Product")
                        .WithMany("Pictures")
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
